### ISSUE TITLE
Contacts and roles

### ISSUE THREAD

**Issue by vivigirardin** [S-ENDA/DMH#1]
Fill out required information on the sheet Role in the [FAIR.xlsx](https://github.com/S-ENDA/DMH/blob/main/FAIR.xlsx) spreadsheet.

- [ ]  NIVA
- [ ]  NILU
- [ ]  NINA
- [ ] #9

**Comment by lisemurberg** [comment]
We need to include an introduction to this chapter before the table of contact and roles. 

Could use some information from  1.2. Human roles in data management, 1.2.2.2. Data producers, 1.2.2.3. Data Management Roles in METs template?

**Comment by lisemurberg** [comment]
@elinahkk add information from METs internal handbook and try to make an introduction/information before the table

**Comment by elinahkk** [comment]
Done!
