### ISSUE TITLE
Data structure and documenting - Table

### ISSUE THREAD

**Issue by lisemurberg** [S-ENDA/DMH#12]
Each institute will fill our their current practices for Structuring and Documenting Data for Efficient Discovery and Use. 

- [ ] MET
- [ ] NILU
- [ ] NINA
- [ ] NIVA

**Comment by vivigirardin** [comment]
I suggest that each one of us ensures that this gets this filled out by the architecture group member in our institute. 

Title suggestion:  _Data Structure and documentation_

**Comment by lisemurberg** [comment]
Text that is in section 2 is not important, but table is important and should be included. From other sections in mets template, 1.1.5 (FAIR), 1.1.3 (datasets) and 1.1.4 (metadata) should be included before the table.

**Comment by lisemurberg** [comment]
Vocabulary should be a part here

**Comment by lisemurberg** [comment]
- [ ] @elinahkk Ask Morten to fill out an example for the table in section 2.3.1 on data formats and data types
