### ISSUE TITLE
Practical guides

### ISSUE THREAD

**Issue by lisemurberg** [S-ENDA/DMH#15]
- [x] Add some MET-specific information on the Practical Guides (from issue #2 )
- [ ] NINA come with examples on practical guides (from issue #5 )

**Comment by elinahkk** [comment]
@lisemurberg information on Practical Guides in METs DMH is similar to what is available on the  [S-enda's guide.](https://s-enda.pages.met.no/data-management-handbook-met/#practical-guides).

**Comment by lisemurberg** [comment]
> @lisemurberg information on Practical Guides in METs DMH is similar to what is available on the [S-enda's guide.](https://s-enda.pages.met.no/data-management-handbook-met/#practical-guides).

@elinahkk I am not able to open the link
