### ISSUE TITLE
Add institute specific structuring and documenting data in struct_institute.md

### ISSUE THREAD

**Issue by lisemurberg** [S-ENDA/DMH#31]
To do for each institute:
- [x] MET
- [x] NILU
- [x] NIVA
- [x] NINA

**Comment by vivigirardin** [comment]
[struct_institute.md](https://github.com/S-ENDA/DMH/blob/main/documentation/struct_institute.md)

**Comment by vivigirardin** [comment]
From NIVA - https://github.com/S-ENDA/DMH/commit/f7cc1132522d3f432164c4b9e90d9840e12f92c0

**Comment by lisemurberg** [comment]
Recommendation: Get the people from the dataset group to write it as they have a better overview!

**Comment by vivigirardin** [comment]
@lisemurberg , @mdsnor : great if you can close this issue before the next workshop
