### ISSUE TITLE
Data Structure and documenting- Systems FAIRness

### ISSUE THREAD

**Issue by vivigirardin** [S-ENDA/DMH#4]
Investigate a way to compare systems fairness

**Comment by lisemurberg** [comment]
In ENVRI-FAIR: 
First a FAIRness assessment + a gap analysis [D8.1 Atmospheric subdomain FAIRness assessment.pdf](https://envri.eu/wp-content/uploads/2020/06/ENVRI-FAIR_D_8-1_Atmospheric-subdomain-FAIRness-assessment.pdf)

From the gap analysis, an implementation plan [D8.3 Atmospheric subdomain implementation plan](https://envri.eu/wp-content/uploads/2020/06/D8.3.pdf)

[https://envri.eu/deliverables/](https://envri.eu/deliverables/ )

**Comment by vivigirardin** [comment]
@lisemurberg , can you create a short presentation for the workshop?

**Comment by lisemurberg** [comment]
@mortenwh Can you provide information from WP4 that can be used in the DMH?

**Comment by mortenwh** [comment]
Please coordinate with Lars-Inge at Kartverket

**Comment by lisemurberg** [comment]
Sendt mail til Lars-Inge 3. august.

**Comment by mortenwh** [comment]
usikker - jeg har en annen adresse. Sender den på slack. Vi bør vel også være forsiktig med å legge mail-adresser i DMH mtp spamming?

**Comment by lisemurberg** [comment]
Translate and include FAIRness assesments used in GeoNorge

Resources: 
[Geonorge Mareano FAIR](
https://register.geonorge.no/data/documents/veiledere_mareano-fair-veileder_v2_fair-veileder-geografiske-data-v2-0202-2022_.pdf)

**Comment by lisemurberg** [comment]
@vivigirardin Spørre Morten om link!

**Comment by vivigirardin** [comment]
> @vivigirardin Spørre Morten om link!

No link, unfortunately. But check page from 29 of 
https://register.geonorge.no/data/documents/veiledere_mareano-fair-veileder_v2_fair-veileder-geografiske-data-v2-0202-2022_.pdf

**Comment by vivigirardin** [comment]
https://register.geonorge.no/mareano-statusregister
