### ISSUE TITLE
New format - mdBook?

### ISSUE THREAD

**Issue by vivigirardin** [S-ENDA/DMH#8]
**Please take a look into this before the next DMH-group update!**

NINA would like to have a flat document, and suggested using [mdBook](https://rust-lang.github.io/mdBook/) to create the document. NIVA and NINA have experience with it. 

MdBook is quite easy to make changes, and it is well documented. A couple of installations are required to run the document locally. [Here is the installation instructions](https://rust-lang.github.io/mdBook/guide/installation.html).

Here is the link to the draft document - https://s-enda.github.io/DMH/

**Comment by lisemurberg** [comment]
I'm ok with this, but I do think we need to make a final decision on format/document structure in the next meeting DMH-group meeting. So that we can focus on the content of the document going forward.

**Comment by mdsnor** [comment]
Thank you, it looks good. Yes, content is the priority. Delivering it with a good format matters too.

**Comment by vivigirardin** [comment]
We stick with MDBook then.
